### PR TITLE
Quita video redmexicoabierto

### PR DESCRIPTION
**Pull request by diegobeauroyre**

### CODE REVIEW

**Comment by diegobeauroyre** [comment]
screen shot 2015-03-24 at 8 41 58 pm

**Comment by diegobeauroyre** [comment]
@jipster wera
@rodowi

**Comment by diegobeauroyre** [comment]
YOLO

**Comment by rodowi** [comment]
<script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=yolo&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>

http://www.google.com/trends/explore?hl=en-US#q=yolo

**Pull request merged**
